import {supabase} from './cloud-save.js';
import {defaultCatalog,validateCatalog,chapterState,audioUrl} from './catalog.js';
const $=id=>document.getElementById(id);let config=structuredClone(defaultCatalog),revision=0,assets=[],users=[],page=0,total=0,popup=null,authorized=false,dirty=false,busy=false;
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const status=t=>$('adminStatus').textContent=t;
function change(){dirty=true;$('draftLabel').textContent='Có thay đổi chưa lưu';}
function button(label,fn){const b=node('button',label);b.type='button';b.onclick=fn;return b;}
function field(title,value,fn,type='text'){const l=node('label',title);const input=node(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=value??'';input.oninput=()=>{fn(input.value);change();};l.append(input);return l;}
function select(title,value,choices,fn){const l=node('label',title),s=node('select');for(const [v,t] of choices){const opt=node('option',t);opt.value=v;s.append(opt);}s.value=value;s.onchange=()=>{fn(s.value);change();};l.append(s);return l;}
function slider(title,value,fn){const l=node('label'),label=node('span',`${title}: ${Math.round(value*100)}%`),r=node('input');r.type='range';r.min=0;r.max=100;r.value=Math.round(value*100);r.oninput=()=>{fn(Number(r.value)/100);label.textContent=`${title}: ${r.value}%`;change();};l.append(label,r);return l;}
function dateInput(iso){return iso?new Date(Date.parse(iso)+7*3600000).toISOString().slice(0,16):'';}
function render(){ $('coverTitle').value=config.headline;$('coverDescription').value=config.intro;$('chapterEditors').replaceChildren();$('audioEditors').replaceChildren();config.chapters.forEach((c,i)=>{
 const card=node('article',undefined,'adminCard'),head=node('div',undefined,'adminChapterHead');head.append(node('h2',`${i+1}. ${c.title}`),node('small',c.id==='chapter-1'?'Đã có game · 4 chặng':'Chương giới thiệu'));card.append(head);
 card.append(field('Tên chương',c.title,v=>c.title=v),field('Giới thiệu',c.description,v=>c.description=v,'textarea'));
 const grid=node('div',undefined,'fieldGrid');grid.append(select('Hiển thị / phát hành',c.status,[['open','Mở'],['soon','Sắp ra mắt'],['scheduled','Hẹn lịch mở'],['locked','Tạm khóa'],['hidden','Ẩn khỏi trang đầu']],v=>c.status=v),field('Giờ mở (Việt Nam · UTC+7)',dateInput(c.releaseAt),v=>c.releaseAt=v?new Date(v+':00+07:00').toISOString():null,'datetime-local'));card.append(grid);
 if(c.id==='chapter-1'){const stages=node('details');stages.append(node('summary','Tên 4 chặng trong Chương 1'));c.stages.forEach((s,j)=>stages.append(field(`Chặng ${j+1}`,s,v=>c.stages[j]=v)));card.append(stages);}else card.append(node('p','Chỉ mở để chơi sau khi bản game của chương này được phát triển. Bạn có thể giới thiệu và hẹn lịch trước.'));
 const controls=node('div',undefined,'adminActions');controls.append(button('Lên',()=>move(i,-1)),button('Xuống',()=>move(i,1)));if(c.id!=='chapter-1')controls.append(button('Bỏ khỏi bản nháp',()=>{if(confirm('Bỏ chương giới thiệu này?')){config.chapters.splice(i,1);change();render();}}));card.append(controls);$('chapterEditors').append(card);
 const audio=node('article',undefined,'adminCard');audio.append(node('h2',c.title));const options=[['','Mặc định theo ngữ cảnh'],...assets.map(a=>[a.name,a.name])];if(c.music&&!assets.some(a=>a.name===c.music))options.push([c.music,c.music]);audio.append(select('Nhạc nền cả chương',c.music,options,v=>c.music=v),slider('Nhạc nền',c.volume,v=>c.volume=v),slider('Chim, gió, mưa & hiệu ứng',c.nature,v=>c.nature=v),slider('Suối',c.water,v=>c.water=v));
 if(c.stages.length){const d=node('details');d.append(node('summary','Thay nhạc riêng cho từng chặng'));c.stages.forEach((s,j)=>{const opts=[['','Theo nhạc của chương'],...assets.map(a=>[a.name,a.name])];if(c.stageAudio[j]&&!opts.some(o=>o[0]===c.stageAudio[j]))opts.push([c.stageAudio[j],c.stageAudio[j]]);d.append(select(s,c.stageAudio[j]||'',opts,v=>c.stageAudio[j]=v));});audio.append(d);}
 audio.append(button('Khôi phục âm thanh mặc định',()=>{c.music='';c.stageAudio={};c.volume=.65;c.nature=.65;c.water=.7;change();render();}));$('audioEditors').append(audio);
 });}
function move(i,dir){const j=i+dir;if(j<0||j>=config.chapters.length)return;[config.chapters[i],config.chapters[j]]=[config.chapters[j],config.chapters[i]];change();render();}
$('coverTitle').oninput=e=>{config.headline=e.target.value;change();};$('coverDescription').oninput=e=>{config.intro=e.target.value;change();};
$('addChapter').onclick=()=>{config.chapters.push({id:'chapter-'+crypto.randomUUID(),title:'Chuyến phiêu lưu mới',description:'Một hành trình mới đang được chuẩn bị.',status:'soon',releaseAt:null,stages:[],music:'',volume:.65,nature:.65,water:.7,stageAudio:{}});change();render();};
async function getAssets(){const {data,error}=await supabase.storage.from('chu-audio').list('',{limit:100,sortBy:{column:'created_at',order:'desc'}});if(error){$('uploadStatus').textContent='Chưa đọc được kho âm thanh. Kiểm tra admin-schema.sql.';return;}assets=(data||[]).filter(a=>audioUrl(a.name));$('audioLibrary').replaceChildren();assets.forEach(a=>{const row=node('div',undefined,'audioRow'),player=node('audio');player.controls=true;player.preload='none';player.src=audioUrl(a.name);row.append(node('span',a.name),player);$('audioLibrary').append(row);});render();}
$('uploadAudio').onclick=async()=>{if(!authorized)return;const file=$('audioUpload').files[0];if(!file||!/^.+\.(mp3|ogg|wav|m4a)$/i.test(file.name)||file.size>20*1024*1024){$('uploadStatus').textContent='Chọn file MP3, OGG, WAV hoặc M4A, tối đa 20 MB.';return;}const ext=file.name.split('.').pop().toLowerCase(),name=crypto.randomUUID()+'.'+ext;$('uploadAudio').disabled=true;const {error}=await supabase.storage.from('chu-audio').upload(name,file,{upsert:false,contentType:{mp3:'audio/mpeg',ogg:'audio/ogg',wav:'audio/wav',m4a:'audio/mp4'}[ext]});$('uploadAudio').disabled=false;if(error){$('uploadStatus').textContent='Tải lên chưa thành công. Kiểm tra quyền quản trị, mạng và bucket chu-audio.';return;}$('uploadStatus').textContent='Đã tải lên. Chọn bài trong cấu hình chương/chặng, rồi lưu và xuất bản.';$('audioUpload').value='';await getAssets();};
async function saveDraft(){validateCatalog(config);const {data,error}=await supabase.rpc('chu_save_draft',{p_config:config,p_revision:revision});if(error)throw error;revision=data.revision;dirty=false;$('draftLabel').textContent=`Bản nháp #${revision} đã lưu`;return data;}
async function action(fn){if(busy||!authorized)return;busy=true;$('saveDraft').disabled=$('publishDraft').disabled=true;try{await fn();}catch(e){status(e.message?.includes('CHU_CONFLICT')?'Bản nháp đã được sửa ở phiên khác. Tải lại trang để lấy bản mới; các thay đổi ở đây chưa được ghi đè.':e.message?.includes('CHU_FORBIDDEN')?'Tài khoản không có quyền quản trị.':`Chưa hoàn tất: ${e.message||'kiểm tra kết nối và SQL.'}`);}finally{busy=false;$('saveDraft').disabled=$('publishDraft').disabled=false;}}
$('saveDraft').onclick=()=>action(async()=>{await saveDraft();status('Đã lưu bản nháp. Người chơi chưa nhận thay đổi.');});
$('publishDraft').onclick=()=>action(async()=>{if(!confirm('Xuất bản cấu hình này cho người chơi?'))return;await saveDraft();const {error}=await supabase.rpc('chu_publish_catalog',{p_revision:revision});if(error)throw error;status('Đã xuất bản. Trang đầu game nhận cấu hình khi mở hoặc sau tối đa 1 phút.');await history();});
$('previewDraft').onclick=()=>{try{validateCatalog(config);$('previewTitle').textContent=config.headline;$('previewIntro').textContent=config.intro;$('previewCards').replaceChildren();config.chapters.filter(c=>c.status!=='hidden').forEach(c=>{const a=node('article',undefined,'adminCard');a.append(node('small',chapterState(c)),node('h3',c.title),node('p',c.description));$('previewCards').append(a);});$('adminPreview').showModal();}catch(e){status(e.message);}};$('closePreview').onclick=()=>$('adminPreview').close();
async function history(){const {data,error}=await supabase.from('chu_catalog_history').select('id,config,actor,created_at').order('id',{ascending:false}).limit(30);if(error){status('Chưa đọc được lịch sử. Kiểm tra SQL và quyền quản trị.');return;}$('historyRows').replaceChildren();for(const h of data){const row=node('article',undefined,'adminCard');row.append(node('h3',`Bản xuất bản #${h.id}`),node('p',new Date(h.created_at).toLocaleString('vi-VN')+' · '+h.actor),button('Đưa vào bản nháp',()=>{if(confirm('Thay nội dung đang chỉnh bằng phiên bản này?')){config=validateCatalog(structuredClone(h.config));change();render();status('Đã đưa phiên bản cũ vào trình chỉnh sửa. Lưu nháp hoặc xuất bản khi đã kiểm tra.');}}));$('historyRows').append(row);}}
async function players(){const term=$('playerSearch').value.trim().replace(/[,()%*]/g,'');let query=supabase.from('chu_profiles').select('user_id,display_name,email,registered_at,last_seen_at',{count:'exact'}).order('registered_at',{ascending:false}).range(page*50,page*50+49);if(term)query=query.or(`email.ilike.%${term}%,display_name.ilike.%${term}%`);const {data,error,count}=await query;if(error){status('Không đọc được danh sách người chơi.');return;}users=data;total=count||0;let progress=[];if(users.length){const r=await supabase.from('chu_progress').select('user_id,snapshot,updated_at').in('user_id',users.map(u=>u.user_id));if(r.error){status('Đã đọc hồ sơ nhưng chưa đọc được tiến trình.');}else progress=r.data;}$('playerRows').replaceChildren();for(const u of users){const row=node('tr'),s=progress.find(p=>p.user_id===u.user_id)?.snapshot;for(const value of [u.display_name||'Chưa có tên',u.email,new Date(u.registered_at).toLocaleString('vi-VN'),new Date(u.last_seen_at).toLocaleString('vi-VN'),s?(s.finished?'Hoàn thành Chương 1':`Chương 1 · Chặng ${Number(s.stage)+1}`):'Chưa lưu'])row.append(node('td',value));$('playerRows').append(row);}$('playerPage').textContent=`Trang ${page+1} · ${total} người`;$('prevPlayers').disabled=page===0;$('nextPlayers').disabled=(page+1)*50>=total;}
$('searchPlayers').onclick=()=>{page=0;players();};$('prevPlayers').onclick=()=>{page=Math.max(0,page-1);players();};$('nextPlayers').onclick=()=>{page++;players();};
$('exportPlayers').onclick=()=>{const cell=v=>'"'+String(/^[\s]*[=+@\-\t\r]/.test(String(v))?"'"+v:v).replaceAll('"','""')+'"';const csv='\ufeff'+[['Tên','Email','Ngày ghi nhận','Hoạt động gần nhất'],...users.map(u=>[u.display_name,u.email,u.registered_at,u.last_seen_at])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=node('a');a.href=url;a.download='chu-nguoi-dang-ky-trang-'+(page+1)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{if(!authorized)return;for(const s of document.querySelectorAll('.adminTab'))s.hidden=s.id!=='tab-'+b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('selected',n===b));if(b.dataset.tab==='players')players();if(b.dataset.tab==='history')history();};
async function verify(){authorized=false;$('adminWorkspace').hidden=true;const {data,error}=await supabase.auth.getUser();if(error||!data.user){$('adminGate').hidden=false;$('adminLogout').hidden=true;status('Đăng nhập để quản lý game.');return;}$('adminIdentity').textContent=`${data.user.email} · UUID: ${data.user.id}`;$('adminLogout').hidden=false;const access=await supabase.rpc('chu_admin_access');if(access.error||!access.data){$('adminGate').hidden=false;status('Chưa có quyền quản trị hoặc chưa chạy admin-schema.sql. Xem hướng dẫn thiết lập bên dưới.');return;}authorized=true;$('adminGate').hidden=true;$('adminWorkspace').hidden=false;const draft=await supabase.from('chu_catalog_draft').select('config,revision').eq('id',1).single();if(draft.error){status('Chưa đọc được bản nháp. Kiểm tra admin-schema.sql.');authorized=false;$('adminWorkspace').hidden=true;$('adminGate').hidden=false;return;}config=validateCatalog(draft.data.config);revision=draft.data.revision;dirty=false;$('draftLabel').textContent=`Bản nháp #${revision}`;render();await getAssets();status('Sẵn sàng. Lưu nháp để chuẩn bị; xuất bản khi bạn muốn áp dụng vào game.');}
$('adminLogin').onclick=async()=>{popup=window.open('about:blank','chu-google-login','popup,width=500,height=680');if(!popup){status('Cho phép cửa sổ bật lên để đăng nhập Google.');return;}const {data,error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:new URL('auth-callback.html',location.href).href,skipBrowserRedirect:true,queryParams:{prompt:'select_account'}}});if(error){popup.close();status('Chưa mở được Google. Kiểm tra cấu hình đăng nhập.');return;}popup.location.replace(data.url);};
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===popup&&e.data?.type==='chu-auth-complete'&&e.data.ok)verify();});
$('adminRetry').onclick=verify;$('adminLogout').onclick=async()=>{if(dirty&&!confirm('Bỏ thay đổi chưa lưu và đăng xuất?'))return;const {error}=await supabase.auth.signOut({scope:'local'});if(error){status('Chưa đăng xuất được.');return;}dirty=false;location.reload();};
supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){authorized=false;$('adminWorkspace').hidden=true;$('adminGate').hidden=false;users=[];$('playerRows').replaceChildren();$('historyRows').replaceChildren();status('Đã đăng xuất. Đăng nhập lại để quản trị.');}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});verify().catch(()=>status('Không thể kết nối. Kiểm tra mạng và cấu hình Supabase.'));
