// Authored story and educational activities. See SOURCES.md for factual references.
const q=(id,title,text,options,correct,lesson)=>({id,title,text,options,correct,lesson});
const observe=(id,title,text)=>({id,title,text});
const stage=(name,badge,theme,tasks)=>({name,badge,theme,tasks});
export const adventures={
 'chapter-2':{title:'Lời hẹn cùng Du',description:'Một lời chào mở đầu tình bạn. Cùng Chu và Du đọc bản đồ, tìm dấu tích cổ xưa và học cách khám phá cùng nhau.',intro:'Tại trạm đón khách, Chu gặp Du đang ôm một cuốn sổ vẽ. Cô kiểm lâm mời hai bạn tham gia hành trình tìm hiểu dấu tích khủng long. Bố của Chu đi cùng cả nhóm.',ending:'Chu và Du đặt hai cuốn sổ cạnh nhau: mỗi bạn nhìn thấy một điều khác biệt, cùng nhau bức tranh trở nên đầy đủ hơn. Hai bạn hẹn tiếp tục chuyến đi bên dòng sông xanh.',stages:[
 stage('Một lời chào, một người bạn','Biết chào hỏi','camp',[
 q('greet','Chào cô kiểm lâm','Cô kiểm lâm đang đón khách ở trạm. Chu muốn hỏi về đường tham quan. Chu nên nói gì?',['Cô ơi, đường đâu?','Cháu chào cô ạ. Cô chỉ giúp cháu đường tham quan được không ạ?','Kéo tay cô rồi chỉ vào bản đồ'],1,'Chu chào hỏi, xưng hô lễ phép và hỏi rõ điều mình cần. Một lời cảm ơn sau khi được giúp khiến cuộc trò chuyện thêm ấm áp.'),
 q('friend','Làm quen với Du','Du đang vẽ một chiếc lá. Chu muốn xem cuốn sổ của bạn.',['Lấy sổ xem ngay','Chê bức vẽ chưa đẹp','Chào Du và hỏi: mình xem cùng được không?'],2,'Chu xin phép trước khi xem đồ của bạn. Du đồng ý và giới thiệu mình; hai bạn cùng bố bắt đầu chuyến đi.'),
 observe('plan','Hẹn điểm gặp nhau','Bố chỉ trạm kiểm lâm có mái xanh làm điểm hẹn. Cả nhóm thống nhất luôn đi cùng nhau, không tự rẽ khỏi đường. Nếu lạc, dừng ở nơi an toàn và nhờ nhân viên có bảng tên giúp liên hệ bố.')]),
 stage('Bản đồ dưới tán cây','Biết lắng nghe','forest',[
 observe('map','Đọc bản đồ cùng Du','Bản đồ của trạm có ba ký hiệu theo đường tham quan: chiếc lá → dấu chân → mặt trời. Du đọc ký hiệu; Chu đối chiếu biển trên đường. Hãy ghi nhớ thứ tự này.'),
 q('route','Chọn lối có biển','Có một lối tắt qua bụi rậm. Đường tham quan chính có ký hiệu chiếc lá và người lớn đi cùng.',['Theo đường có biển cùng bố và Du','Chia nhóm để tìm đường nhanh hơn','Tự chui vào bụi rậm'],0,'Đi theo đường được phép giúp cả nhóm giữ liên lạc. Khi chưa chắc đường, dừng ở điểm an toàn và hỏi người phụ trách.'),
 {id:'maplock',title:'Ghép lộ trình',text:'Chọn đủ ba ký hiệu theo thứ tự ghi trên bản đồ.',sequence:['Chiếc lá','Dấu chân','Mặt trời'],requires:['map']}]),
 stage('Dấu tích trong đá','Nhà quan sát nhỏ','fossil',[
 observe('fossil','Quan sát mẫu trưng bày','Trên bàn là bản sao hóa thạch bàn tay Iguanodon. Điểm nổi bật là gai lớn ở ngón cái. Cô hướng dẫn giải thích: hình dáng này khác chiếc sừng trên mũi mà người ta từng hình dung.'),
 q('thumb','Chiếc gai nằm ở đâu?','Du vẽ lại mẫu bàn tay vừa quan sát. Chu giúp bạn đặt chiếc gai vào vị trí nào?',['Trên đỉnh đầu','Ở ngón cái của bàn tay','Giữa lưng'],1,'Iguanodon có gai lớn ở ngón cái. Quan sát hóa thạch giúp các nhà khoa học chỉnh sửa những hình dung trước đây.'),
 q('keep','Nếu thấy đá có dấu lạ','Bên đường có một viên đá giống mẫu trưng bày. Chu nên làm gì?',['Đập ra tìm xương','Bỏ vào ba lô làm kỷ niệm','Giữ nguyên vị trí, báo bố và người phụ trách'],2,'Chu không tự đào, đập hoặc mang mẫu đi. Giữ nguyên vị trí giúp người có chuyên môn kiểm tra cả dấu tích lẫn lớp đá xung quanh.')]),
 stage('Lời hẹn trên đồi gió','Người bạn đáng tin','ridge',[
 q('wait','Du cần nghỉ chân','Du nói mình mỏi chân và muốn uống nước. Chu sắp đến điểm ngắm cảnh.',['Chạy trước để giữ chỗ','Báo bố, cùng Du nghỉ tại điểm cho phép','Giục Du đi nhanh hơn'],1,'Chu lắng nghe bạn, báo người lớn và cùng nghỉ. Đi cùng nhau quan trọng hơn đến trước.'),
 q('lost','Nếu không thấy nhóm','Trong bài tập của cô kiểm lâm, Chu giả sử vừa nhận ra mình không còn nhìn thấy bố.',['Dừng ở nơi an toàn, nhờ nhân viên có bảng tên giúp liên hệ bố','Chạy theo người lạ bảo biết đường','Đi sâu vào rừng để tìm'],0,'Không đi theo người lạ hoặc chạy tìm khắp nơi. Dừng ở nơi an toàn, tìm nhân viên phụ trách để được giúp và không tự rời điểm hẹn.'),
 q('thanks','Kết thúc chuyến đi','Cô kiểm lâm trao lại sổ quan sát. Hai bạn nên làm gì trước khi về?',['Đi ngay không nói gì','Xin thêm quà trước','Cảm ơn, chào cô và đi cùng bố'],2,'Chu và Du cảm ơn cô đã hướng dẫn, chào tạm biệt rồi cùng bố về điểm hẹn. Tình bạn bắt đầu từ những điều tử tế.')])]},
 'chapter-3':{title:'Theo dòng sông xanh',description:'Men theo dòng nước uốn quanh chân núi, Chu và Du khám phá dấu tích sự sống, chọn lối đi an toàn và gìn giữ màu xanh của rừng.',intro:'Dòng sông phía dưới đồi dẫn đến một khu trưng bày ngoài trời. Chu, Du và bố theo đường ven sông có hàng rào. Tiếng chim xen với tiếng nước; mỗi điểm dừng lại mở ra một câu hỏi mới.',ending:'Nhìn dòng sông từ đài quan sát, Chu và Du hiểu rằng khám phá không cần phải liều lĩnh. Hai bạn giữ lại những trang ghi chép, để lại bờ sông sạch đẹp và mang lời hẹn đến thung lũng khủng long.',stages:[
 stage('Bến nước đầu rừng','Biết dừng đúng lúc','river',[
 q('ranger','Xin hướng dẫn ở bến','Bác phụ trách đang kiểm tra biển báo. Chu muốn biết lối đi nào đang mở.',['Tự vượt rào đi xuống bến','Cháu chào bác ạ, hôm nay nhóm cháu đi lối nào được ạ?','Gọi lớn rồi bỏ đi'],1,'Chu chào bác, hỏi đường được phép và cảm ơn. Cả nhóm làm theo hướng dẫn hiện tại ở khu tham quan.'),
 q('bank','Quả bóng bên mép nước','Một quả bóng trôi sát bờ. Du muốn lấy nhưng bờ dốc và ướt.',['Tự bước xuống lấy nhanh','Nhờ Chu giữ áo rồi với xuống','Đứng xa mép nước và báo người lớn'],2,'Không tự xuống nước hoặc với ra mép bờ để lấy đồ. Đồ vật có thể thay thế; an toàn của mình và bạn luôn quan trọng hơn.'),
 observe('waternote','Nhìn dòng chảy','Từ sau hàng rào, Chu nhìn lá trôi theo dòng. Mặt nước êm không cho biết chắc độ sâu hay sức nước. Cả nhóm chỉ quan sát ở vị trí được phép.')]),
 stage('Khúc quanh có cây cầu','Chọn lối an toàn','bridge',[
 observe('bridgeboard','Đọc biển cây cầu','Lối tham quan có cầu cố định và tay vịn. Cô phụ trách xác nhận cầu đang mở; cả nhóm chờ hướng dẫn trước khi qua. Không dùng cây đổ hoặc đá giữa suối làm đường tắt.'),
 q('cross','Qua cầu như thế nào?','Bố đã kiểm tra lối đi. Chu và Du chuẩn bị qua cầu.',['Đi bình tĩnh cùng bố, theo hướng dẫn và giữ tay vịn','Chạy thi qua cầu','Leo lên lan can để ngắm nước'],0,'Đi cùng người lớn, không chạy đùa hay leo lan can. Nếu cầu đóng hoặc nước dâng, dừng lại và chọn tuyến được người phụ trách hướng dẫn.'),
 q('bottle','Nước uống cho cả nhóm','Du thấy nước suối rất trong. Bố có bình nước uống đã chuẩn bị.',['Múc suối uống thử','Dùng nước trong bình và nghỉ ở điểm an toàn','Cúi xuống sát mặt nước'],1,'Dùng nước uống đã chuẩn bị. Nước nhìn trong vẫn không thể được đánh giá an toàn để uống chỉ bằng mắt.')]),
 stage('Những trang đá cổ','Đọc dấu tích xưa','fossil',[
 observe('diplodocus','Cổ dài trong trang đá','Bảng trưng bày giới thiệu Diplodocus: khủng long ăn thực vật với cổ và đuôi rất dài, sống vào cuối kỷ Jura. Bản sao giúp hai bạn nhận ra dáng cổ dài mà không cần chạm vào mẫu thật.'),
 q('diet','Diplodocus ăn gì?','Dựa vào bảng thông tin, Chu nên đặt thẻ nào cạnh hình Diplodocus?',['Thịt cá','Bánh ngọt của khách','Thực vật'],2,'Diplodocus là khủng long ăn thực vật. Cổ dài giúp nó tiếp cận cây lá ở những vị trí khác nhau; không có nghĩa mọi loài cổ dài đều giống nhau.'),
 q('evidence','Điều nào là bằng chứng?','Du thấy hình khủng long màu xanh trong truyện và mẫu xương ở khu trưng bày.',['Màu trong truyện chứng minh màu thật','Hóa thạch giúp nghiên cứu cơ thể; màu của mô hình là lựa chọn minh họa','Tranh và hóa thạch đều là xương thật'],1,'Hóa thạch là bằng chứng để nghiên cứu sự sống cổ. Màu sắc và cử động trong game được minh họa, không phải bản phục dựng khoa học chính xác.')]),
 stage('Giữ màu xanh cho dòng sông','Bạn của thiên nhiên','river',[
 q('litter','Một mảnh rác sắc cạnh','Hai bạn thấy mảnh kính gần thùng rác trên đường.',['Báo người lớn hoặc nhân viên, không cầm tay trần','Nhặt ngay bằng tay','Đá xuống sông cho khuất mắt'],0,'Không chạm vào kính, kim hoặc đồ sắc lạ. Chu báo nhân viên để xử lý bằng dụng cụ phù hợp; không đẩy rác xuống nước.'),
 q('rain','Trời chuyển mưa','Mây tối kéo đến và bác phụ trách thông báo đóng đường ven sông.',['Cố đi hết đoạn vì sắp tới nơi','Ra bờ sông xem nước lên','Theo bố về nơi trú được hướng dẫn'],2,'Khi tuyến đường đóng, cả nhóm quay lại theo hướng dẫn. Không nán lại bờ nước để xem nước dâng, không trú dưới cây cao đơn độc.'),
 {id:'rivercode',title:'Ba bước khám phá an toàn',text:'Sắp thứ tự hành động khi gặp một lối đi chưa rõ an toàn.',sequence:['Dừng ở nơi an toàn','Hỏi người lớn đi cùng','Theo hướng dẫn được phép']}])]},
 'chapter-4':{title:'Thung lũng những người bạn lớn',description:'Gặp gỡ những dáng hình khác biệt: cổ dài, ba sừng, lưng giáp và đuôi chùy. Cùng Chu và Du hoàn thành sổ khám phá khủng long ăn thực vật.',intro:'Cô hướng dẫn mở cổng thung lũng triển lãm. Bốn khu quan sát tái hiện các khủng long ăn thực vật khác nhau. Đây là công viên tưởng tượng: những loài xuất hiện cùng nhau trong game không nhất thiết sống cùng thời hay cùng nơi ngoài lịch sử Trái Đất.',ending:'Cuốn sổ có thêm những dáng hình và tên gọi mới. Du vẽ một chiếc lá ở trang cuối; Chu viết: “Mỗi loài đều có câu chuyện riêng. Mình quan sát, tìm bằng chứng và luôn tôn trọng thiên nhiên.” Chuyến đi tiếp theo vẫn đang chờ phía trước.',stages:[
 stage('Đồng cỏ cổ dài','Nhận ra Diplodocus','sauropod',[
 observe('longneck','Quan sát Diplodocus','Từ hàng rào, Chu và Du nhận ra cổ dài, thân lớn và đuôi dài của Diplodocus. Đây là một khủng long ăn thực vật sống vào cuối kỷ Jura. Những cây lá trong khu trưng bày giúp hình dung nguồn thức ăn.'),
 q('identify','Ghép tên với hình dáng','Loài vừa quan sát có cổ và đuôi rất dài. Tên trên bảng là gì?',['Triceratops','Diplodocus','Ankylosaurus'],1,'Diplodocus có cổ và đuôi dài. Chu đối chiếu đặc điểm với bảng thông tin, không chỉ đoán bằng màu của mô hình.'),
 q('feed','Giữ đồ ăn trong ba lô','Du có một chiếc bánh. Khủng long đang cúi ăn cây lá phía trong hàng rào.',['Ném bánh để gọi lại gần','Đưa tay qua hàng rào','Giữ bánh, chỉ quan sát và làm theo nhân viên'],2,'Không tự cho động vật ăn hoặc đưa tay qua hàng rào. Thức ăn và việc chăm sóc thuộc trách nhiệm của người phụ trách.')]),
 stage('Khu vườn ba sừng','Nhận ra Triceratops','horned',[
 observe('horns','Quan sát Triceratops','Triceratops có hai sừng lớn phía trên mắt, một sừng nhỏ trên mũi và diềm xương phía sau đầu. Dù có sừng nổi bật, nó là khủng long ăn thực vật.'),
 q('three','Những chiếc sừng kể gì?','Chu thấy sừng và hàm của Triceratops trên bảng. Điều nào đúng?',['Có sừng nên chắc chắn ăn thịt','Ba sừng có nghĩa là biết bay','Đây là khủng long ăn thực vật'],2,'Sừng không quyết định một loài ăn thịt hay ăn thực vật. Nhà khoa học xem xét các bằng chứng như răng, hàm và hóa thạch.'),
 q('distance','Bạn lớn vẫn cần khoảng cách','Một con trong khu trưng bày quay đầu về phía nhóm.',['Đứng tại điểm quan sát, không gọi lớn hoặc vượt rào','Chạy tới để chụp gần','Vỗ hàng rào thật mạnh'],0,'Trông hiền hoặc ăn thực vật không có nghĩa có thể đến gần. Chu và Du quan sát bình tĩnh ở vị trí được phép.')]),
 stage('Lối đi giữa những tấm giáp','Phân biệt hai người bạn','armored',[
 observe('plates','Stegosaurus và tấm lưng','Stegosaurus là khủng long ăn thực vật, có các tấm xương dựng trên lưng và gai ở đuôi. Nó sống vào cuối kỷ Jura. Quan sát hình dáng giúp Chu phân biệt với loài có đuôi chùy.'),
 observe('club','Ankylosaurus và đuôi chùy','Ankylosaurus có thân thấp, giáp xương trên cơ thể và phần chùy ở cuối đuôi. Nó cũng là khủng long ăn thực vật. Đây là một dáng hình khác hẳn người bạn cổ dài.'),
 q('compare','Ghép đúng đặc điểm','Du cần hai nhãn cho tranh. Cặp nào đúng?',['Stegosaurus: ba sừng; Ankylosaurus: cổ dài','Stegosaurus: tấm lưng và gai đuôi; Ankylosaurus: giáp và đuôi chùy','Cả hai đều có cánh'],1,'Stegosaurus nổi bật với tấm lưng và gai đuôi. Ankylosaurus nổi bật với giáp cơ thể và chùy đuôi. Đều ăn thực vật nhưng hình dáng rất khác nhau.')]),
 stage('Cuốn sổ của hai nhà khám phá','Người kể chuyện khoa học','museum',[
 observe('iguanodon','Gặp lại Iguanodon','Chu nhớ mẫu bàn tay ở chuyến đi cùng Du. Iguanodon là khủng long ăn thực vật có gai lớn ở ngón cái. Cô hướng dẫn nhắc hai bạn: một đặc điểm nhỏ cũng giúp nhận ra sự khác biệt.'),
 {id:'museumcode',title:'Ghép sổ quan sát',text:'Chọn lần lượt tên theo ba đặc điểm: cổ dài → ba sừng → đuôi chùy.',sequence:['Diplodocus','Triceratops','Ankylosaurus']},
 q('farewell','Một lời cảm ơn trước khi về','Cô hỏi hai bạn học được gì ở thung lũng.',['Mọi khủng long đều giống nhau','Có thể vuốt ve mọi loài ăn cỏ','Cháu cảm ơn cô. Chúng cháu biết quan sát đặc điểm và giữ khoảng cách ạ.'],2,'Hai bạn chào và cảm ơn cô. Khám phá khoa học bắt đầu từ quan sát cẩn thận, biết hỏi và sẵn sàng học thêm.')]) ]}
};
export const implementedIds=['chapter-1',...Object.keys(adventures)];
