import {adventures,implementedIds} from './adventures.js';
import {supabase} from './cloud-save.js';
import {SUPABASE_URL} from './supabase-config.js';
export const defaultCatalog={headline:'Mỗi trang mở ra một thế giới.',intro:'Cùng Chu khám phá thiên nhiên, kết bạn và học những điều nhỏ bé để lớn lên. Chuyến đi đầu tiên chỉ là khởi đầu.',chapters:[
{id:'chapter-1',title:'Quả trứng thất lạc',description:'Một cuốn truyện cũ, những dấu chân bí ẩn và chuyến đi cùng bố để đưa quả trứng về nhà.',status:'open',releaseAt:null,stages:['Khu rừng thì thầm','Hang ánh sáng','Thung lũng bị lãng quên','Đường về tổ ấm'],music:'',volume:.65,nature:.65,water:.7,stageAudio:{}},
...Object.entries(adventures).map(([id,a])=>({id,title:a.title,description:a.description,status:'soon',contentVersion:2,releaseAt:null,stages:a.stages.map(s=>s.name),music:'',volume:.65,nature:.65,water:.7,stageAudio:{}}))
]};
export let catalog=structuredClone(defaultCatalog);let clockOffset=0,refreshing=null;
export function audioUrl(path){return typeof path==='string'&&/^[a-zA-Z0-9/_\-.]+\.(mp3|ogg|wav|m4a)$/i.test(path)&&!path.includes('..')?`${SUPABASE_URL}/storage/v1/object/public/chu-audio/${path}`:'';}
export function validateCatalog(v){if(!v||typeof v.headline!=='string'||v.headline.length>100||typeof v.intro!=='string'||v.intro.length>500||!Array.isArray(v.chapters)||!v.chapters.length||v.chapters.length>100)throw new Error('Nội dung trang mở đầu chưa hợp lệ.');const ids=new Set();for(const c of v.chapters){if(!/^chapter-[a-z0-9-]+$/.test(c.id)||ids.has(c.id)||typeof c.title!=='string'||!c.title.trim()||c.title.length>100||typeof c.description!=='string'||c.description.length>500||!['open','soon','scheduled','hidden','locked'].includes(c.status))throw new Error('Thông tin chương chưa hợp lệ.');ids.add(c.id);if(c.status==='scheduled'&&!Number.isFinite(Date.parse(c.releaseAt)))throw new Error('Chọn ngày giờ mở chương.');if(!Array.isArray(c.stages)||c.stages.length>20||c.stages.some(x=>typeof x!=='string'||x.length>100))throw new Error('Tên chặng chưa hợp lệ.');for(const key of ['volume','nature','water'])if(typeof c[key]!=='number'||c[key]<0||c[key]>1)throw new Error('Âm lượng phải từ 0 đến 100%.');if(c.music&&!audioUrl(c.music))throw new Error('Đường dẫn âm thanh chưa hợp lệ.');if(!c.stageAudio||Array.isArray(c.stageAudio)||typeof c.stageAudio!=='object')throw new Error('Cấu hình âm thanh chặng chưa hợp lệ.');for(const [key,value] of Object.entries(c.stageAudio))if(!/^[0-9]+$/.test(key)||typeof value!=='string'||(value&&!audioUrl(value)))throw new Error('Âm thanh chặng chưa hợp lệ.');}if(!ids.has('chapter-1'))throw new Error('Giữ Chương 1 để tương thích tiến trình hiện tại.');if(v.chapters.find(c=>c.id==='chapter-1').stages.length!==4)throw new Error('Chương 1 hiện có đúng 4 chặng.');return v;}
export function available(c,now=Date.now()+clockOffset){return !!c&&implementedIds.includes(c.id)&&(c.status==='open'||c.status==='scheduled'&&Date.parse(c.releaseAt)<=now);}
export function chapterState(c){if(c.status==='hidden')return 'Sắp ra mắt';if(c.status==='locked')return 'Tạm khóa';if(!implementedIds.includes(c.id))return 'Sắp ra mắt';if(available(c))return 'Sẵn sàng khám phá';if(c.status==='scheduled')return 'Hẹn ngày mở';return 'Sắp ra mắt';}
export async function refreshCatalog(){if(refreshing)return refreshing;refreshing=fetchCatalog();try{return await refreshing;}finally{refreshing=null;}}
async function fetchCatalog(){try{const {data,error}=await supabase.rpc('chu_get_catalog').abortSignal(AbortSignal.timeout(8000));if(error)throw error;if(data?.config){catalog=validateCatalog(upgradeCatalog(data.config));clockOffset=Date.parse(data.server_now)-Date.now();try{localStorage.setItem('chu-public-catalog',JSON.stringify(catalog));}catch{}return true;}}catch{}try{const cached=JSON.parse(localStorage.getItem('chu-public-catalog'));if(cached)catalog=validateCatalog(upgradeCatalog(cached));}catch{}return false;}
export function currentAudio(stage,chapterId='chapter-1'){const c=catalog.chapters.find(c=>c.id===chapterId)||defaultCatalog.chapters[0];return {url:audioUrl(c.stageAudio?.[stage]||c.music),music:c.volume,nature:c.nature,water:c.water};}
export function upgradeCatalog(value,admin=false){const v=structuredClone(value);for(const base of defaultCatalog.chapters){if(!v.chapters.some(c=>c.id===base.id))v.chapters.splice(Math.min(Number(base.id.split('-')[1])-1,v.chapters.length),0,{...structuredClone(base),status:'soon'});}for(const c of v.chapters){const a=adventures[c.id];if(!a)continue;if(c.description.startsWith('Dự kiến:'))c.description=a.description;if(!c.stages?.length)c.stages=a.stages.map(s=>s.name);if(admin)c.contentVersion=2;}return v;}
export function mountCover({play,account}){const $=id=>document.getElementById(id);function render(){ $('coverHeadline').textContent=catalog.headline;$('coverIntro').textContent=catalog.intro;const list=$('chapterCards');list.replaceChildren();catalog.chapters.forEach((c,i)=>{const article=document.createElement('article');article.className='chapterCard '+(available(c)?'isPlayable':'');const number=document.createElement('span');number.className='chapterNumber';number.textContent=String(/^chapter-[1-4]$/.test(c.id)?Number(c.id.split('-')[1]):i+1).padStart(2,'0');const badge=document.createElement('span');badge.className='chapterBadge';badge.textContent=chapterState(c);const h=document.createElement('h3');h.textContent=c.title;const p=document.createElement('p');p.textContent=c.description;article.append(number,badge,h,p);if(!available(c)){const caption=document.createElement('p');caption.className='chapterCaption';caption.textContent=c.upcomingCaption||'Chu đang chuẩn bị chuyến đi mới. Hẹn bạn trở lại để cùng khám phá nhé!';article.append(caption);}if(c.releaseAt&&c.status==='scheduled'){const date=document.createElement('small');date.textContent='Mở vào: '+new Date(c.releaseAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'});article.append(date);}if(c.stages.length){const detail=document.createElement('details');const summary=document.createElement('summary');summary.textContent=`${c.stages.length} chặng trong chương`;detail.append(summary);const ul=document.createElement('ol');c.stages.forEach(name=>{const li=document.createElement('li');li.textContent=name;ul.append(li)});detail.append(ul);article.append(detail);}const b=document.createElement('button');b.textContent=available(c)?'Khám phá chương này':chapterState(c);b.disabled=!available(c);b.onclick=async()=>{b.disabled=true;b.textContent='Đang mở…';const fresh=await refreshCatalog();if(!fresh){b.disabled=false;b.textContent='Chưa kết nối được · thử lại';return;}const current=catalog.chapters.find(x=>x.id===c.id);if(available(current))await play(c.id);render();};article.append(b);list.append(article);});}
 $('coverContinue').onclick=account;render();refreshCatalog().then(render);setInterval(()=>{if(!$('cover').hidden)refreshCatalog().then(render);},60000);const refresh=()=>{if(!$('cover').hidden)refreshCatalog().then(render);};window.addEventListener('chu-cover-open',refresh);window.addEventListener('focus',refresh);window.addEventListener('storage',e=>{if(e.key==='chu-catalog-published-at')refresh();});return {render,refresh};}
