import {createClient} from './vendor/supabase.js';
import {SUPABASE_URL,SUPABASE_KEY} from './supabase-config.js';
export const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{flowType:'pkce',detectSessionInUrl:false,persistSession:true,autoRefreshToken:true,storageKey:'chu-google-session-v1'}});
export function setupCloud({snapshot,restore,reset,hold,release,hasStarted}){
 const $=id=>document.getElementById(id),panel=$('accountPanel');
 let selectedChapter='chapter-1';let user=null,loaded=false,remote=null,revision=0,unresolved=false,busy=false,dirty=false,queued=false,lastSaved='',popup=null,previousFocus=null,initDone=false,epoch=0;
 function status(text){$('saveStatus').textContent=text;}
 function message(text){$('accountMessage').textContent=text;}
 function render(){const signed=!!user;$('saveChapter').value=selectedChapter;$('saveChapter').disabled=hasStarted()||busy;$('accountLabel').textContent=signed?'Tài khoản':'Đăng nhập';$('accountIdentity').textContent=signed?(user.email||'Đã đăng nhập Google'):'Chơi khách · chưa đồng bộ';$('googleLogin').hidden=signed;$('signOut').hidden=!signed;$('saveNow').hidden=!signed;$('loadCloud').hidden=!remote;$('saveNow').disabled=busy||!loaded||!hasStarted();$('loadCloud').disabled=busy;$('saveNow').textContent=unresolved?'Lưu hành trình này thay bản cũ':'Lưu tiến trình ngay';}
 function show(exit=false){if(!panel.open){previousFocus=document.activeElement;hold();panel.showModal();} $('exitChoices').hidden=!exit;$('leaveGame').textContent=user?'Lưu và về màn hình đầu':'Thoát không lưu';render();$('accountClose').focus();}
 function close(){panel.close();}
 panel.addEventListener('close',()=>{release();previousFocus?.focus();});$('accountClose').onclick=close;
 $('account').onclick=()=>show();$('exitGame').onclick=()=>{show(true);message(user?'Lưu thành công trước khi thoát để có thể tiếp tục trên thiết bị khác.':'Bạn chưa đăng nhập. Thoát sẽ mất hành trình đang chơi. Bạn muốn đăng nhập Google để lưu hay thoát không lưu?');};
 $('keepPlaying').onclick=close;
 $('leaveGame').onclick=async()=>{if(user&&hasStarted()){if(unresolved){message('Hãy chọn bản lưu muốn giữ trước khi thoát.');return;}if(!await save(true)){message('Chưa lưu được. Bạn có thể thử lại, chơi tiếp hoặc chọn bỏ tiến trình chưa lưu.');$('discardExit').hidden=false;return;}}finishExit();};
 function finishExit(){dirty=false;lastSaved='';$('discardExit').hidden=true;close();reset();status(user?'Đã thoát · bản lưu trên tài khoản được giữ':'Chơi khách · không lưu tiến trình');}
 $('discardExit').onclick=()=>{if(confirm('Bỏ tiến trình chưa lưu và về màn hình đầu?'))finishExit();};
 $('signOut').onclick=async()=>{if(hasStarted()&&!confirm('Đăng xuất sẽ kết thúc phiên chơi này. Phần chưa đồng bộ sẽ bị bỏ. Tiếp tục?'))return;const {error}=await supabase.auth.signOut({scope:'local'});if(error){message('Chưa đăng xuất được. Hãy thử lại.');return;}dirty=false;close();reset();};
 async function load(){if(!user)return;const id=user.id,ticket=++epoch;loaded=false;render();status('Đang kiểm tra bản lưu…');try{const {data,error}=await supabase.from('chu_progress').select('snapshot,revision,updated_at').eq('user_id',id).eq('chapter_id',selectedChapter).maybeSingle();if(error)throw error;if(ticket!==epoch||user?.id!==id)return;remote=data;revision=data?.revision||0;loaded=true;unresolved=!!data;status(data?'Có bản lưu trên tài khoản':'Đã đăng nhập · sẵn sàng lưu');message(data?'Tài khoản có bản lưu. Chọn “Tiếp tục bản trên tài khoản”, hoặc lưu hành trình đang chơi để thay bản cũ.':'Đã đăng nhập. Tiến trình sẽ tự đồng bộ trong khi chơi.');render();if(data){if(hasStarted())show();}else if(hasStarted())await save();}catch{if(ticket!==epoch)return;status('Chưa kết nối được dữ liệu');message('Chưa tải được bản lưu. Hãy kiểm tra kết nối mạng và bấm thử lại. Hành trình đang chơi vẫn được giữ khi bạn còn ở trang này.');render();}}
 async function profile(){if(!user)return;const {error}=await supabase.rpc('chu_sync_profile');if(error)message('Chưa cập nhật được hồ sơ. Hãy kiểm tra kết nối mạng và thử lại.');}
 async function syncSession(){const {data,error}=await supabase.auth.getUser();const next=error?null:data.user;if(next?.id===user?.id&&initDone)return;initDone=true;if(user&&next?.id!==user.id){reset();}epoch++;user=next;loaded=false;remote=null;revision=0;unresolved=false;lastSaved='';dirty=hasStarted();render();if(user){await profile();await load();}else{status('Chơi khách · không lưu tiến trình');message('Đăng nhập Google để lưu hành trình và tiếp tục trên thiết bị khác. Chỉ dùng tên và email, không truy cập hộp thư.');}}
 async function save(force=false){if(!user||!loaded||!hasStarted()||unresolved)return false;if(busy){queued=true;return false;}const s=snapshot();if(s.chapterId!==selectedChapter)return false;const encoded=JSON.stringify(s);if(encoded===lastSaved&&!force)return true;const id=user.id,ticket=epoch;busy=true;render();status('Đang lưu…');try{const {data,error}=await supabase.rpc('chu_save_progress',{p_snapshot:s,p_expected_revision:revision});if(error)throw error;if(ticket!==epoch||user?.id!==id)return false;revision=data.revision;remote=data;lastSaved=encoded;dirty=JSON.stringify(snapshot())!==encoded;status('Đã đồng bộ lên tài khoản');message('Đã lưu tiến trình thành công.');return true;}catch(error){dirty=true;status('Chưa lưu được · đừng đóng trang');if(error?.message?.includes('CHU_CONFLICT')){loaded=false;await load();message('Bản lưu đã thay đổi trên thiết bị khác. Chọn bản muốn tiếp tục trước khi lưu.');}else message('Lưu chưa thành công. Hãy kiểm tra kết nối mạng rồi bấm thử lại. Đừng đóng trang để giữ hành trình đang chơi.');return false;}finally{busy=false;render();if(queued){queued=false;setTimeout(()=>save(),300);}}}
 async function selectChapter(id){if(busy||hasStarted()||!/^chapter-[1-4]$/.test(id))return false;selectedChapter=id;epoch++;loaded=false;remote=null;revision=0;unresolved=false;lastSaved='';render();if(user)await load();return selectedChapter===id;}
 $('saveChapter').onchange=()=>selectChapter($('saveChapter').value);
 $('retryCloud').onclick=()=>user?load():syncSession();
 $('saveNow').onclick=async()=>{if(unresolved){if(!confirm('Thay bản lưu trên tài khoản bằng hành trình đang chơi?'))return;unresolved=false;}await save(true);};
 $('loadCloud').onclick=()=>{if(!remote)return;if(hasStarted()&&!confirm('Bỏ hành trình đang chơi và tiếp tục bản trên tài khoản?'))return;const data=remote.snapshot;if(!restore(data)){message('Chưa thể mở bản lưu: chương có thể đang khóa hoặc dữ liệu chưa được hỗ trợ. Hành trình hiện tại được giữ nguyên.');return;}unresolved=false;dirty=false;lastSaved=JSON.stringify(snapshot());status('Đang chơi bản đã đồng bộ');close();};
 $('googleLogin').onclick=async()=>{if(popup&&!popup.closed){popup.focus();return;}popup=window.open('about:blank','chu-google-login','popup,width=500,height=680');if(!popup){message('Hãy cho phép cửa sổ bật lên cho trang này rồi bấm lại. Hành trình của bạn vẫn được giữ.');return;}message('Hoàn tất đăng nhập trong cửa sổ Google, rồi quay lại game.');try{const {data,error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:new URL('auth-callback.html',location.href).href,skipBrowserRedirect:true,queryParams:{prompt:'select_account'}}});if(error)throw error;popup.location.replace(data.url);}catch{popup.close();message('Chưa mở được đăng nhập Google. Bạn hãy thử lại sau; hành trình đang chơi vẫn được giữ khi bạn còn ở trang này.');}};
 window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===popup&&e.data?.type==='chu-auth-complete'){if(e.data.ok)syncSession();else message('Đăng nhập chưa hoàn tất. Bạn hãy thử lại; hành trình đang chơi vẫn còn.');}});
 supabase.auth.onAuthStateChange((event)=>{if(['SIGNED_IN','SIGNED_OUT'].includes(event))setTimeout(syncSession,0);});
 window.addEventListener('beforeunload',e=>{if(hasStarted()&&(!user||dirty||busy||unresolved||!loaded||JSON.stringify(snapshot())!==lastSaved)){e.preventDefault();e.returnValue='';}});
 setInterval(()=>{if(hasStarted()){dirty=JSON.stringify(snapshot())!==lastSaved;save();}},15000);
 window.addEventListener('online',()=>{if(user){if(!loaded)load();else save();}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});
 syncSession();
 return {changed(){dirty=hasStarted();if(user)save();},get signedIn(){return !!user;},open:()=>show(),selectChapter,exit:()=>{$('exitGame').onclick();}};
}
